---
- name: Common
  hosts: all
  tasks:
  - name: Add Laptop SSH Key
    ansible.posix.authorized_key:
      user: emerson
      path: /home/emerson/.ssh/authorized_keys
      state: present
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8yKvzEsZEuJIASSWj6qTRq4oOnehKCPIC9yqzFcgxxKV1bGMUtYJMsi9YdDSramgG02ZRplKPudAT072vYL3KQ0JLewXsoSdCHW7TlzSHL4dPGBoYOaxsoUAxWIYtkph+TMJ78Z8pA76Q/NEiBBQL7ATvgJRSkDAaFnxpgtzaOfDa8+/d1enfFb7jAZaDFcWClLL4BkWRIhUCdxc6lLPCssmEhQlaab5/zGLtZ3zAu975IBHH1XwnbwHCUB4ENZpeYcSIJvz291y4l4S6Mp0QCck5rRqjnQzwza+5rww59WxaZ9KwoYGQ0TTVuIwupd032aAJAe/B7Yv9hB65FbAz8zkr7S/sKJkY8/vxZ2dGpfZttnWKj6PClpbATzcFvJCIzGR9NaOCX0A+ClGTsvZhppeOo9qzj6Axe3tumXU+uJNyixQHVx0rZxoxSA1bpfpewOKVild7L7P45G3uF7gd1kocQ5YrmpTg66r82Ztwa6v0CcJUpPOVvpx1Clf3lm8="
      comment: "emerson@iphone"
  - name: Update packages
    ansible.builtin.apt:
      update_cache: true
  - name: Install Neovim
    ansible.builtin.apt:
      name: neovim
      state: present
  - name: Upgrade packages
    ansible.builtin.apt:
      name: "*"
      state: latest
  - name: Ensure neovim config folder exists
    ansible.builtin.file:
      path: /home/emerson/.config/nvim
      state: directory
      recurse: true
  - name: Copy Neovim config
    ansible.builtin.copy:
      src: files/neovim.conf
      dest: /home/emerson/.config/nvim/init.vim
  - name: Add neovim alias
    ansible.builtin.blockinfile:
      dest: /home/emerson/.bashrc
      create: true
      insertbefore: BOF
      marker: '# {mark} ANSIBLE MANAGED BLOCK - neovim'
      block: |
        alias vim=nvim
- name: Head
  hosts: head
  tasks:
  - name: Install tmux
    ansible.builtin.apt:
      update_cache: true
      name: tmux
      state: present
  - name: Copy tmux config
    ansible.builtin.copy:
      src: files/tmux.conf
      dest: /home/emerson/.tmux.conf
