---
- name: Common
  hosts: all
  roles:
    - common
- name: Proxmox
  hosts: proxmox
  roles:
    - proxmox
- name: VMs
  hosts: vms
  roles:
    - vms
- name: Head
  hosts: head
  roles:
    - head
- name: Nginx
  hosts: nginx
  roles:
    - nginx
