---
- name: Common
  hosts: all
  roles:
    - common
- name: Head
  hosts: head
  roles:
    - head
- name: NFS
  hosts: nfs
  roles:
    - nfs
- name: Plex
  hosts: plex
  roles:
    - plex
- name: OpenVPN
  hosts: openvpn
  roles:
    - openvpn
- name: Seedbox
  hosts: seedbox
  roles:
    - seedbox
- name: Nextcloud
  hosts: nextcloud
  roles:
    - nextcloud
- name: Nginx
  hosts: nginx
  roles:
    - nginx
- name: MC Friends
  hosts: mc_friends
  roles:
    - mc_friends
- name: Docker
  hosts: docker
  roles:
    - docker
