---
- name: Common
  hosts: all
  roles:
    - common
- name: Head
  hosts: head
  roles:
    - head
- name: NFS
  hosts: nfs
  roles:
    - nfs
- name: Plex
  hosts: plex
  roles:
    - plex
- name: Nginx
  hosts: nginx
  roles:
    - nginx
