---
- name: Install tmux
  ansible.builtin.apt:
    update_cache: true
    name: tmux
    state: present
- name: Copy tmux config
  ansible.builtin.copy:
    src: files/tmux.conf
    dest: /home/emerson/.tmux.conf
    owner: emerson
    group: emerson
