---
- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
- name: Reload nut-client
  ansible.builtin.systemd:
    name: nut-client
    state: reloaded
- name: Reload nut-monitor
  ansible.builtin.systemd:
    name: nut-monitor
    state: reloaded
