---
- name: Copy rsyslog Config
  ansible.builtin.copy:
    src: 01-client.conf
    dest: /etc/rsyslog.d/01-client.conf
    owner: root
    group: root
  notify: Restart rsyslog
- name: Ensure certs folder exists
  ansible.builtin.file:
    path: /etc/ssl/certs/rsyslog
    state: directory
    recurse: true
    owner: root
    group: root
- name: Copy rsyslog CA cert
  ansible.builtin.copy:
    src: ca.pem
    dest: /etc/ssl/certs/rsyslog/ca.pem
    owner: root
    group: root
- name: Install common packages    
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - linux-cpupower
- name: Set CPU governor  
  ansible.builtin.command:
    cmd: cpupower frequency-set -g {{ cpu_governor }}
  changed_when: false

- include_tasks: nut.yml
