---
- name: Install Proxmox packages
  ansible.builtin.apt:
    state: present
    package:
      - sudo
      - vim
      - rsyslog
- name: Copy rsyslog Config
  ansible.builtin.copy:
    src: 01-client.conf
    dest: /etc/rsyslog.d/01-client.conf
    owner: root
    group: root
  notify: Restart rsyslog
