---
- name: Mount Swarm NFS
  ansible.posix.mount:
    src: nas.emwj.lan:/Swarm
    path: /mnt/swarm
    opts: defaults,user,nolock
    state: mounted
    fstype: nfs
- name: Mount NFS
  ansible.posix.mount:
    src: nas.emwj.lan:/Plex
    path: /mnt/Plex
    opts: defaults,user
    state: mounted
    fstype: nfs
