---
- name: Mount Swarm NFS
  ansible.posix.mount:
    src: nas.vm.emwj.lan:/Swarm
    path: /mnt/swarm
    opts: defaults,user,nolock
    state: mounted
    fstype: nfs
- name: Mount Plex NFS
  ansible.posix.mount:
    src: nas.vm.emwj.lan:/Plex
    path: /mnt/Plex
    opts: defaults,user
    state: mounted
    fstype: nfs
- name: Mount Storage NFS
  ansible.posix.mount:
    src: nas.vm.emwj.lan:/Storage
    path: /mnt/Storage
    opts: defaults,user
    state: mounted
    fstype: nfs

