---
- include_tasks: ssh_keys.yml
- include_tasks: packages.yml
- include_tasks: configs.yml
- include_tasks: rsyslog.yml

- name: Vacuum Logs
  ansible.builtin.command:
    cmd: journalctl --vacuum-time=2d
