---
- name: Install Packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - qemu-guest-agent
      - nfs-common
- name: Upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
- name: Make sure qemu guest agent is running
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: qemu-guest-agent
  when: not ansible_check_mode
