- name: Make sure qBittorrent is running
  ansible.builtin.systemd:
    state: started
    name: qbittorrent
- name: Make sure bad service is running
  ansible.builtin.systemd:
    state: started
    name: idontexist
- name: Make sure NFS Plex is mounted
  ansible.posix.mount:
    fstype: nfs
    src: 192.168.1.101:/home/emerson/ext/Plex
    path: /home/emerson/Plex
    opts: defaults
    state: mounted
- name: Make sure NFS Storage is mounted
  ansible.posix.mount:
    fstype: nfs
    src: 192.168.1.101:/home/emerson/ext/Storage
    path: /home/emerson/Storage
    opts: defaults
    state: mounted
