- name: Make sure qBittorrent is running
  ansible.builtin.systemd:
    state: started
    name: qbittorrent
- name: Make sure NFS Plex is mounted
  ansible.posix.mount:
    fstype: nfs
    src: nfs.emwj.lan:/home/emerson/ext/Plex
    path: /home/emerson/Plex
    opts: defaults
    state: mounted
- name: Make sure NFS Storage is mounted
  ansible.posix.mount:
    fstype: nfs
    src: nfs.emwj.lan:/home/emerson/ext/Storage
    path: /home/emerson/Storage
    opts: defaults
    state: mounted
