---
- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
- name: Reload systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: reloaded
