---
- name: Install common packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - neovim
      - rsyslog
      - rsyslog-gnutls
      - curl
      - sudo
      - vim
