---
- name: Install common debian packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    package:
      - nfs-common
      - neovim
      - rsyslog
      - rsyslog-gnutls
      - curl
      - sudo
      - vim
      - htop
  when: distro == "debian" or distro == "ubuntu" 

- name: Install EPEL Repo
  ansible.builtin.dnf:
    state: present
    update_cache: true
    name:
      - epel-release
  when: distro == "rocky"

- name: Install common RHEL packages
  ansible.builtin.dnf:
    state: present
    update_cache: true
    name:
      - nfs-utils
      - neovim
      - rsyslog
      - rsyslog-gnutls
      - curl
      - sudo
      - vim
      - htop
  when: distro == "rocky"
