---
- name: Make sure sudo group exists
  ansible.builtin.group:
    name: sudo
    state: present
- name: Add emerson user
  ansible.builtin.user:
    name: emerson
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "$6$kI8Fi4F01xKugIjg$vgc2kWihrrXKBy3TnOjZWfMNAd/Mk3M0uPSF3I/i6aNYDqL3BqZmBqgHdKQKdgpYEQqBGVIzvNkC00x7hsIqS/"
- name: Add laptop SSH key
  ansible.posix.authorized_key:
    user: emerson
    path: /home/emerson/.ssh/authorized_keys
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCg7U6kuT1/zt/Y7P83JhkdEfyWQDU3FZxE8umFjI6kJTLAK7N3IgVz+ihPwRwA4bc1PRFZBYkt3tlQ8pFWCBRMTyMMYOkEiFFrwgQNqXzkj1btfY3QiAqdK2KN3ICLxFjzouwdBrMonb/mI0GneyIe+CbCYrglphNxog91u1ElOYc5PAKWWlmqDhWjbRlrBTcnkucOkwrh0g3vJ19WFQL6/ufx/h3tIrrj+ZUuQkl883X1e1mFk9dB28FrO+LUxSqnak+Xa58b/HY87tzxoBGSVZ8H5jSnntZ4NaDwKgdVysCvJeKiugJvVCORVzef5REiPwR1ZCMBSbADcJDIMR+uY/Nq+tTOl47qA6Q6MGtSobbs6XnZyHYHnJX2lrom2HnHoyzJ2g73EPRFfOaHpPrpx8zV23MurbzSfJzuLsBWtBxuNV2/9nF7I3CTp3ZEOFTtSs4wgcbFjHsCRIjly/H+fkDRBBPux5/Z1+uH5aEVAAVChl45EC/I+8qKZA1DpFc="
    comment: "emerson@iphone"
- name: Add head SSH key
  ansible.posix.authorized_key:
    user: emerson
    path: /home/emerson/.ssh/authorized_keys
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiYOmZu42ZYq6QvCC+DSv/0R9HldnGH4co8/w/NFYP38jj+UwHm3CaLkxK6B1YyZxw8rJIW1DNP6XV5Dd06BEPyXOBZT+hYRqEIEV7Cx+dMoVVhoRQAF+taUAX3iRlbozldokqNLaaCTc1ly1j+Oot+NbsGP184+yVlna37wPFZ3+2oXvHLLCMumiYek5XAIG7z3fRuJqnc3jdpzEmeVCg9cEhlPUaHY9wKkEwlOILFZmTVxIbYu3GEF5e9ZFjMQ1rEtT/OlvEuYgn+CC+NB4swAQFxgkAC0tbRKDPv+bjsb+/3tNx9DQJ01YKArx5+v3YXN9e/bvZknrrVVRTCvvy1u33K2ZZ+Uu3FrR9Mx09jgarGLGIyWqXfOr8XXWhtqTx/4WlBVC5ak2A++V0XBNtO+XQuBbzAvzore1102Svg7hgDwYrnOY1Ta3HZp94/AjDGzYlGbjTfmqiqwsB7z5zc9euBIDIikw2yoyOYr0t58PJw+m2tseZvqTFlR4fJjk="
    comment: "emerson@head"
