- name: Make sure portfolio is running
  community.docker.docker_compose:
    project_src: /home/emerson/emwj.dev/
    project_name: portfolio
    state: present
- name: Make sure cloudflare-ddns is running
  community.docker.docker_compose:
    project_src: /home/emerson/cloudflare-ddns/
    project_name: cloudflare-ddns
    state: present
- name: Make sure CLU is running
  community.docker.docker_compose:
    project_src: /home/emerson/CLU/
    project_name: clu
    state: present
